from app import app, db
from sqlalchemy import inspect, text

print("===== AMINATION ESPORTS HIGHLIGHTS MIGRATION =====")

with app.app_context():
    backend = db.engine.url.get_backend_name()
    print("Database:", backend)

    if backend != "postgresql":
        raise RuntimeError(
            "Migration refused: this script must run against PostgreSQL."
        )

    inspector = inspect(db.engine)
    tables = set(inspector.get_table_names())

    print()
    print("===== HIGHLIGHT TABLE =====")

    if "highlight" in tables:
        print("highlight: EXISTS")
    else:
        print("highlight: CREATING")

        db.session.execute(
            text(
                """
                CREATE TABLE highlight (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR(150) NOT NULL,
                    player_id INTEGER NULL,
                    tournament_id INTEGER NULL,
                    description TEXT NULL,
                    video_url VARCHAR(1000) NOT NULL,
                    is_published BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMP NOT NULL,
                    published_at TIMESTAMP NULL,
                    CONSTRAINT fk_highlight_player
                        FOREIGN KEY (player_id)
                        REFERENCES player (id),
                    CONSTRAINT fk_highlight_tournament
                        FOREIGN KEY (tournament_id)
                        REFERENCES tournament (id)
                )
                """
            )
        )

        db.session.commit()

        print("highlight: CREATED")

    print()
    print("===== VERIFICATION =====")

    inspector = inspect(db.engine)

    if "highlight" not in inspector.get_table_names():
        raise RuntimeError(
            "Migration verification failed: highlight table does not exist."
        )

    for column in inspector.get_columns("highlight"):
        print(
            f'{column["name"]} '
            f'({column["type"]}) '
            f'nullable={column["nullable"]}'
        )

    print()
    print("SUCCESS: Highlight table exists and was verified.")

print("===== DONE =====")
